{
 "title": "HVAC",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "HVAC High Pressure (PSI)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    { "expr": "hvac_high_press_sys1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HVAC Low Pressure (PSI)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    { "expr": "hvac_low_press_sys1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HVAC Compressor Demand",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "hvac_comp1_demand_percentage", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Room Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "hvac_room_temp_f", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}