{
 "title": "LOCAL POWER METERS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CENTENNIAL_A - PWR_MTR_PRI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "voltsAB{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "voltsBC{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "voltsCA{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 2 }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "ampsA{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "ampsB{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "ampsC{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 4 }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "freq{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "angleVoltsAB{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "angAB"
      },
      {
       "expr": "angleVoltsBC{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "angBC"
      },
      {
       "expr": "angleVoltsCA{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "angCA"
      }
     ]
    }
   ]
  },
  {
   "title": "CENTENNIAL_A - PWR_MTR_HVAC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "voltsAB{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "voltsBC{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "voltsCA{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 9 }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "ampsA{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "ampsB{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "ampsC{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 11 }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "freq{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "angleVoltsAB{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "angAB"
      },
      {
       "expr": "angleVoltsBC{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "angBC"
      },
      {
       "expr": "angleVoltsCA{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "angCA"
      }
     ]
    }
   ]
  },
  {
   "title": "CENTENNIAL_A - PWR_MTR_SEC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "voltsAB{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "voltsBC{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "voltsCA{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 16 }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "ampsA{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "ampsB{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "ampsC{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 18 }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "freq{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "angleVoltsAB{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "angAB"
      },
      {
       "expr": "angleVoltsBC{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "angBC"
      },
      {
       "expr": "angleVoltsCA{truck=\"CENTENNIAL_A\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "angCA"
      }
     ]
    }
   ]
  },
  {
   "title": "CENTENNIAL_B - PWR_MTR_PRI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "voltsAB{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "voltsBC{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "voltsCA{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 23 }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "ampsA{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "ampsB{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "ampsC{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 25 }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "freq{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "angleVoltsAB{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "angAB"
      },
      {
       "expr": "angleVoltsBC{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "angBC"
      },
      {
       "expr": "angleVoltsCA{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_PRI\"}",
       "legendFormat": "angCA"
      }
     ]
    }
   ]
  },
  {
   "title": "CENTENNIAL_B - PWR_MTR_HVAC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "voltsAB{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "voltsBC{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "voltsCA{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 30 }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "ampsA{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "ampsB{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "ampsC{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 32 }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "freq{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "angleVoltsAB{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "angAB"
      },
      {
       "expr": "angleVoltsBC{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "angBC"
      },
      {
       "expr": "angleVoltsCA{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_HVAC\"}",
       "legendFormat": "angCA"
      }
     ]
    }
   ]
  },
  {
   "title": "CENTENNIAL_B - PWR_MTR_SEC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "voltsAB{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "voltsBC{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "voltsCA{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 37 }
     ]
    },
    {
     "title": "Current",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "ampsA{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "ampsB{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "ampsC{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 39 }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "freq{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "angleVoltsAB{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "angAB"
      },
      {
       "expr": "angleVoltsBC{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "angBC"
      },
      {
       "expr": "angleVoltsCA{truck=\"CENTENNIAL_B\", job=\"modbus\", device=\"PWR_MTR_SEC\"}",
       "legendFormat": "angCA"
      }
     ]
    }
   ]
  }
 ]
}