{
 "title": "UDX Warnings",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Average Core Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(core_temp_c{job_type=\"cobalt\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Core Temp - Last 1H",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(core_temp_c{job_type=\"cobalt\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Core Temp - Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(core_temp_c{job_type=\"cobalt\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDX Core Temps",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "core_temp_c{job_type=\"cobalt\"}",
     "legendFormat": "{{card_name}}"
    }
   ]
  }
 ]
}